import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`bg-linear-to-br from-gray-950 via-zinc-900 to-stone-900 text-white`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        {/* header */}
        <main className="relative min-h-screen container mx-auto pt-40 md:pt-32">
          {/* glow */}
          <div>{children}</div>

        {/* footer */}
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
